### ISSUE TITLE
/datasets API interpreting modification date as creation date

### ISSUE THREAD

**Issue by justinasr** [dmwm/dbs2go#15]
I believe I found a bug in the `/datasets` API. I was trying to fetch what was modified since X, but some datasets were missing. I narrowed problem down to `min_ldate` and `min_cdate` behaving strangely. After some digging through code here: https://github.com/dmwm/dbs2go/blob/af364c15950a305ec542a6c5a3b07432ed7e1c0a/dbs/datasets.go#L129-L181 I noticed that for both `min_cdate`/`max_cdate` and `min_ldate`/`max_ldate` query uses `D.CREATION_DATE`. I think it should be `D.LAST_MODIFICATION_DATE` in 3 places in the second `if`.

Now it is essentially impossible to query for "datasets changed since X".

**Comment by vkuznet** [comment]
Justinas, thanks for reporting the issue (and nailed down to precise part of the code). I fixed it in the following commit 3c02bd0 and will schedule shortly the test on testbed. Do you have any specific datasets to look at that I can test the changes

**Comment by justinasr** [comment]
I _noticed for_ and was using `/BTagCSV/Run2016B-ver1_HIPM_UL2016_MiniAODv2_NanoAODv9-v1/NANOAOD`. It was INVALIDated at some point, but our tools still show it as VALID.
Dataset: https://cmsweb.cern.ch/dbs/prod/global/DBSReader/datasets?dataset=/BTagCSV/Run2016B-ver1_HIPM_UL2016_MiniAODv2_NanoAODv9-v1/NANOAOD&dataset_access_type=*&detail=1

We know that it was VALID at `1627509903` and it's last modification date is `1647455348`, but if I do
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/datasets?dataset=/BTagCSV/Run2016B-ver1_HIPM_UL2016_MiniAODv2_NanoAODv9-v1/NANOAOD&dataset_access_type=*&detail=1&min_ldate=1627509903

I get `[]`.

**Comment by justinasr** [comment]
Can confirm that it works. Thanks for the prompt fix!
Issue can be closed.
