### ISSUE TITLE
fake error from submitMigration ?

### ISSUE THREAD

**Issue by belforte** [dmwm/dbs2go#63]
this is from my script
```
INFO:Logger:Submiting migration request for block /ST_t-channel_top_4f_InclusiveDecays_TuneCP5CR1_13TeV-powheg-madspin-pythia8/RunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v1/NANOAODSIM#6377b8d7-4919-4855-969c-145976c7509a ...
```
then script does
```
result = migrateApi.submitMigration(data)
```
and this is what I got on stdout, with `result` being undefined. What does it mean ? this happens in a loop which
inserts migration requests, is there a race among server threads which try to insert something at same time ? Maybe that's intentional and properly handled but then.. why return error ?
```
DBS Server error: [{'error': {'reason': 'DBSError Code:110 Description:DBS DB insert record error Function:dbs.migrate.SubmitMigration Message: Error: nested DBSError Code:110 Description:DBS DB insert record error Function:dbs.migration_requests.Insert Message: Error: ORA-00001: unique constraint (CMS_DBS3_K8S_PHYS_OWNER.TUC_MR_1) violated\n', 'message': '', 'function': 'dbs.migrate.SubmitMigration', 'code': 125}, 'http': {'method': 'POST', 'code': 400, 'timestamp': '2022-07-13 22:17:26.605424376 +0000 UTC m=+43595.659041335', 'path': '/dbs/int/phys03/DBSMigrate/submit', 'user_agent': 'DBSClient/Unknown/', 'x_forwarded_host': 'cmsweb-testbed.cern.ch:8443', 'x_forwarded_for': '137.138.31.168', 'remote_addr': '188.185.121.219:26377'}, 'exception': 400, 'type': 'HTTPError', 'message': 'DBSError Code:125 Description:DBS Migration error Function:dbs.migrate.SubmitMigration Message: Error: nested DBSError Code:110 Description:DBS DB insert record error Function:dbs.migrate.SubmitMigration Message: Error: nested DBSError Code:110 Description:DBS DB insert record error Function:dbs.migration_requests.Insert Message: Error: ORA-00001: unique constraint (CMS_DBS3_K8S_PHYS_OWNER.TUC_MR_1) violated\n'}]
ERROR:Logger:Migration request failed to submit.
HTTP Error 400: Bad Request
```
OTOH it looks like migration request is submitted properly, since if I try again a bit later I find that block was migrated.

I can retry after exceptions etc. etc.,  but I think we can do better. Also if I go that way, I could end up overloading migration server with multiple useless requests.

**Comment by vkuznet** [comment]
Stefano, there few issues you touched here:
- the undefined `result` variable, I think it is Python issue since undefined means that the `submitMigration` API does not properly handle parsing of submit API output and therefore the return result is undefined. I can have a look into Python code but so far I concentrate on server side
- the actual error from DBSMigrate server which reports `ORA-00001: unique constraint (CMS_DBS3_K8S_PHYS_OWNER.TUC_MR_1)`. The Go server process requests sequentially and so far we have single migration server (I'm working on supporting multiple ones). The error means that indeed the given migration input is already in DB which implies that it was submitted. I think in this case server correctly return proper error since client asked to migrate the same input. I already added a check for given migration input in migration server and it returns a proper message that given migration request is already in the system.

So, I think the actual issue here is not in migration server but rather in logic of the client. Can you provide me exact code that I can look at. I can also use your dataset to test in my local setup.

**Comment by belforte** [comment]
I beg to disagree.
I think this was a server problem, here server does not return a json document.

It is supposed to always do that, in case with the message that this block migration is already in progress.
IIUC you modified the server so this should not happen any more.

I think that server should return an exception only in two cases:
1. malformed input (to be spotted in testing and debugged)
2. server problem (which may always happen in production and will be retried)

If you want the client to stop retrying, you need to send a proper JSON document which says so.

Exact code is exactly dbsApi.submitMigration() using testbed/DBSmigrate as dbsApi.

**Comment by vkuznet** [comment]
Stefano, the server ALWAYS return JSON, either it fails or succeed. What I'm saying that for whatever reason the client fails to parse provided JSON. You provided the following:
```
DBS Server error: [{'error': {'reason': 'DBSError Code:110 Description:DBS DB insert record error Function:dbs.migrate.SubmitMigration Message: Error: nested DBSError Code:110 Description:DBS DB insert record error Function:dbs.migration_requests.Insert Message: Error: ORA-00001: unique constraint (CMS_DBS3_K8S_PHYS_OWNER.TUC_MR_1) violated\n', 'message': '', 'function': 'dbs.migrate.SubmitMigration', 'code': 125}, 'http': {'method': 'POST', 'code': 400, 'timestamp': '2022-07-13 22:17:26.605424376 +0000 UTC m=+43595.659041335', 'path': '/dbs/int/phys03/DBSMigrate/submit', 'user_agent': 'DBSClient/Unknown/', 'x_forwarded_host': 'cmsweb-testbed.cern.ch:8443', 'x_forwarded_for': '137.138.31.168', 'remote_addr': '188.185.121.219:26377'}, 'exception': 400, 'type': 'HTTPError', 'message': 'DBSError Code:125 Description:DBS Migration error Function:dbs.migrate.SubmitMigration Message: Error: nested DBSError Code:110 Description:DBS DB insert record error Function:dbs.migrate.SubmitMigration Message: Error: nested DBSError Code:110 Description:DBS DB insert record error Function:dbs.migration_requests.Insert Message: Error: ORA-00001: unique constraint (CMS_DBS3_K8S_PHYS_OWNER.TUC_MR_1) violated\n'}]

```
which shows the JSON which includes the error. And, in Go there is no exception, that's why I don't understand what you are asking for. The exception exists in python client which may fail or not, or can throw exception. What I'm asking is that you provide me exact code or github pointer to `dbsApi.submitMigration()`, in other words where is `submitMigration` API? It is somewhere either in DBS client or in CRAB publisher.

**Comment by belforte** [comment]
>  where is submitMigration API?

https://github.com/dmwm/DBSClient/blob/be292dca5b82f72a8cf9bf13e7dc263232ab7b16/src/python/dbs/apis/dbsClient.py#L1803-L1812

sorry for my confused writing. Yes, it is JSON but it is not a list of migration ids values as expected.
Of course the return value of the POST call for submit is not documented in 
https://github.com/dmwm/dbs2go/blob/master/docs/apis.md#dbs-migrate-server-post-apis
so you can easily say that whatever is there is correct.
But I was not expecting this, I was expecting a JSON with migration_id (possibly 0 if there was nothing to migrate) and status of that migration. In case the migration is in status 1 (which I gather means it is being acted upon) it does not matter
if it was started already or server was so fast. If I get an exception I need to retry, and since it is still in progress, I get an exception again !

Anyhow, it looks like we are converging here.

**Comment by belforte** [comment]
> So, I think the actual issue here is not in migration server but rather in logic of the client. Can you provide me exact code that I can look at. I can also use your dataset to test in my local setup.

Looking at DBSClient code (see pointer above) it looks that simply every time HTTP call returns an error an http_exeption is 
raised. This makes a lot of sense IMHO, and I still think that server should not return an http error in this case.
I do not like that client (CRAB) would need to parse the error message text in order to decide what to do,  in particular getting an ORA-,...... error and treating it as "all fine" looks very dangerous here. As you described there are many migrations kicked off and therefore many database operations done, how can I know that the insertion which failed was a harmless one ?

**Comment by vkuznet** [comment]
ok, I added example of output from submit API to https://github.com/dmwm/dbs2go/blob/master/docs/apis.md#dbs-migrate-server-post-apis and it should be similar to python API as I followed the later logic. It provides all details client's need to know about migration request. Please review and let me know. Please note, that all Go based response are representation of struct data type (an object with attributes) and I standarize the output, i.e. you always will get list from DBS servers across all APIs, the list contains a dict (not numbers). Such standard output format allows to write common/generic parsers without guessing if you get different data-types from the server. And, such as in case of Reader/Writer, the difference in Go vs Py servers are handled in a client. As such we can have different implementations.

Since my reply crossed with yet another reply of yours I will answer about http_exception. Please try to understand that exception is pure PYTHON construct, it does not exist in other languages and does not exist in curl. The DBS server should be transparent to implementation and clients. As such its API should return the same if client will be python or curl. As such, DBS server provide a list of dictionary object. This dict object represent standard DBS error, i.e. it contains error code, reason, message. Such error are common across DBS Reader, Writer and Migration servers. All DBS errors now have generic format. This makes API implementation easy and we may start using different clients, i.e. we can use python or switch to curl, or switch to Go without worry how implementation is done. You should not parse ORA- error. In WMCore we created a DBSError class to handle that, see https://github.com/dmwm/WMCore/pull/11173,  such that you can use this class to get meaning code or message, etc. out of ANY DBS server error.

Regarding how you should treat errors. You should only rely on migration_status code which I described in migration documentation. If status code is 1 it means that migration is in progress, etc. I don't think your code need to do anything else. In other words, here is workflow you should do in your code:
- submit migration request using submitMigration DBS Client API
- now you have a choice, you can either migration request id to check your migration request status or you may use migration_input
- to check your migration I suggest you use migation_input

**Comment by belforte** [comment]
sure. All I wanted to say is that it is much better that is the case discussed here server returns
an actual migrationId with status=1 ,rather than `DBSError Code:125`

**Comment by belforte** [comment]
so in the end I have to modify migration status checking inside CRAB Publisher to use block names, not migrationIds, to keep track.

I will write a new publishing script to run in parallel to current one, inserting in int/phys03 every user output which we currently insert in prod/phys03.  This will trigger lots of migrations since very little of prod/global is already in int (just a guess). So maybe we can do it just a little bit at a time as a start.

**Comment by vkuznet** [comment]
ok, are we settle on this then? My view that having full output will help debugging the issue easier. But client should use `/status` API to get status of migration.  

Bottom line, if you have status=1 you must wait since DBS migration server is doing something with migration, if you have status=0 the migration is not yet started, therefore you should not resubmit anything since migration request is already in place. Then, if status=2 you are ok, i.e. migration is finished, all other codes will indicate the error one way or another. Finally, if there is no migration requests then you'll get empty list, e.g.
```
# check status of non-existing migration request
curl "http://localhost:9898/dbs2go-migrate/status?migration_rqst_id=123"
[]
```

Does it clear?

Do I need to do anything for this ticket?

**Comment by vkuznet** [comment]
ohh, this is different error and is related to host certificates, does your client has valid proxy? I'll need to check testbed certificates now.

**Comment by belforte** [comment]
the message is not about my client proxy. Other calls work finely. It looks to me to be in communication between migration server and prod/global.

**Comment by vkuznet** [comment]
Stefano this issue is now fixed on testbed. I successfully migration your block using new version. I used my dev end-point /dbs2go-migrate which migrate data to phys01 DB backend. Therefore, you may try to migrate this block again using CRAB and int/phys03. I suggest to close this issue as resolved. Please let me know.

**Comment by belforte** [comment]
need to wait for https://its.cern.ch/jira/browse/CMSKUBERNETES-165 to be solved in order to validate

**Comment by vkuznet** [comment]
the issue with DBSMIgrate DB on testbed is solved, please proceed.

**Comment by belforte** [comment]
as mentioned in https://github.com/dmwm/dbs2go/issues/64#issuecomment-1194213967 I still get the error message listed at the top `Error: ORA-00001: unique constraint (CMS_DBS3_K8S_PHYS_OWNER.TUC_MR_1) violated` which gives me no information on what to do to solve.

**Comment by belforte** [comment]
this was solved.
