### ISSUE TITLE
persistent migration request failure

### ISSUE THREAD

**Issue by belforte** [dmwm/dbs2go#64]
every time i submit a request to migrate this block
/SingleMuon/Run2017E-UL2017_MiniAODv2-v1/MINIAOD#1d522d75-7490-4fff-9a21-198abe0b2bb9
from cmsweb:prod/global to cmsweb-testbed:int/phys03
I get simply an HTTP 502 error (from FE I presume), after quite some time.
I tried to issue the request while doing tail -f of the log file on vocms0750//cephfs/testbed/dbs-logs

There are relevant lines in the log file dbs2go-phys03-m-cd7b66669-wq25h.log-20220714 like

[2022-07-14 08:21:42.32667597 +0000 UTC m=+30415.379444134] migrate.go:614: Migration request for /SingleMuon/Run2017E-UL2017_MiniAODv2-v1/MINIAOD#1d522d75-7490-4fff-9
a21-198abe0b2bb9 {MIGRATION_REQUEST_ID:0 MIGRATION_URL:https://cmsweb.cern.ch/dbs/prod/global/DBSReader MIGRATION_INPUT:/SingleMuon/Run2017E-UL2017_MiniAODv2-v1/MINIAOD#1d522d75-7490-4fff-9a21-198abe0b2bb9 MIGRATION_STATUS:0 CREATE_BY:/DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it CREATION_DATE:1657786902 LAST_MODIFIED_BY:/DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it LAST_MODIFICATION_DATE:1657786902 RETRY_COUNT:0}

but then there are many messages from validator.go and then activity drops to only ping and metrics and I get HTTP 502

Looks to me like FE never receives a signal that server got the request.

As far as I can tell, this can be consistently replicated now, but I can't tell if there's a bug or simply log is so verbose that server gets slowed down.

**Comment by belforte** [comment]
to be specific, my code is:
```ptython
result=None
print(apiMig.url)
print(data)
try:
    result = apiMig.submitMigration(data)
except Exception as ex:
    print('**exception raised**:\n %', str(ex))
    # sometime this simply means "block is there already"
    if result:
        status = result[0]['migration_details']['migration_status']
        if status == 4:
            print(status)
            msg = "Block is already at destination."
            logger.info(msg)
            print(msg)
    print(result)
print(type(result))
if isinstance(result, list):
    result=result[0]
    status = result['migration_details']['migration_status']
    if status == 4:
        print(status)
        msg = "Block is already at destination."
        logger.info(msg)
#print(result)
print('end')
```
and the output is
```
https://cmsweb-testbed.cern.ch:8443/dbs/int/phys03/DBSMigrate
{'migration_url': 'https://cmsweb.cern.ch/dbs/prod/global/DBSReader', 'migration_input': '/SingleMuon/Run2017E-UL2017_MiniAODv2-v1/MINIAOD#1d522d75-7490-4fff-9a21-198abe0b2bb9'}
**exception raised**:
 % HTTP Error 502: 
URL=https://cmsweb-testbed.cern.ch:8443/dbs/int/phys03/DBSMigrate/submit
Code=502
Message=Proxy Error
Header=HTTP/1.1 502 Proxy Error
Date: Thu, 14 Jul 2022 09:05:18 GMT
Server: Apache
Content-Length: 472
Content-Type: text/html; charset=iso-8859-1


Body=<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/auth/complete/dbs/int/phys03/DBSMigrate/submit">POST&nbsp;/auth/complete/dbs/int/phys03/DBSMigrate/submit</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
</body></html>


None
<class 'NoneType'>
end
```

**Comment by belforte** [comment]
N.B. I picked that dataset by looking in ES (monit_prod_condor_raw_metric* index)  at what people are currently processing with CRAB 
https://monit-kibana.cern.ch/kibana/app/kibana#/discover?_g=(filters:!(),refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(data.CRAB_Workflow,data.DESIRED_CMSDataset),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b66f4510-cd98-11ea-9887-713cbbe6612f,key:data.CMS_SubmissionTool,negate:!f,params:(query:CRAB),type:phrase,value:CRAB),query:(match:(data.CMS_SubmissionTool:(query:CRAB,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b66f4510-cd98-11ea-9887-713cbbe6612f,key:data.Status,negate:!f,params:(query:Completed),type:phrase,value:Completed),query:(match:(data.Status:(query:Completed,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b66f4510-cd98-11ea-9887-713cbbe6612f,key:data.CRAB_UserHN,negate:!t,params:(query:sciaba),type:phrase,value:sciaba),query:(match:(data.CRAB_UserHN:(query:sciaba,type:phrase))))),index:b66f4510-cd98-11ea-9887-713cbbe6612f,interval:auto,query:(language:lucene,query:''),sort:!(metadata.timestamp,desc))

**Comment by vkuznet** [comment]
Stefano, this issue is now fixed on testbed. I successfully migration your block using new version. I used my dev end-point `/dbs2go-migrate` which migrate data to phys01 DB backend. Therefore, you may try to migrate this block again using CRAB and int/phys03.

**Comment by vkuznet** [comment]
From my point of view this issue is resolved, therefore, upon your confirmation I want to close it.

**Comment by belforte** [comment]
Sorry, I still get error, although a different one:

https://cmsweb-testbed.cern.ch:8443/dbs/int/phys03/DBSMigrate
{'migration_url': 'https://cmsweb.cern.ch/dbs/prod/global/DBSReader', 'migration_input': '/SingleMuon/Run2017E-UL2017_MiniAODv2-v1/MINIAOD#1d522d75-7490-4fff-9a21-198abe0b2bb9'}
DBS Server error: [{'error': {'reason': 'DBSError Code:110 Description:DBS DB insert record error Function:dbs.migrate.SubmitMigration Message: Error: nested DBSError Code:110 Description:DBS DB insert record error Function:dbs.migration_requests.Insert Message: Error: ORA-00904: "MIGRATION_SERVER": invalid identifier\n', 'message': '', 'function': 'dbs.migrate.SubmitMigration', 'code': 125}, 'http': {'method': 'POST', 'code': 400, 'timestamp': '2022-07-23 12:31:11.609885045 +0000 UTC m=+23565.943754432', 'path': '/dbs/int/phys03/DBSMigrate/submit', 'user_agent': 'DBSClient/Unknown/', 'x_forwarded_host': 'cmsweb-testbed.cern.ch:8443', 'x_forwarded_for': '188.184.30.135', 'remote_addr': '10.100.59.128:36964'}, 'exception': 400, 'type': 'HTTPError', 'message': 'DBSError Code:125 Description:DBS Migration error Function:dbs.migrate.SubmitMigration Message: Error: nested DBSError Code:110 Description:DBS DB insert record error Function:dbs.migrate.SubmitMigration Message: Error: nested DBSError Code:110 Description:DBS DB insert record error Function:dbs.migration_requests.Insert Message: Error: ORA-00904: "MIGRATION_SERVER": invalid identifier\n'}

Maybe as simple as "something is wrong in testbed atm". I get this
Error: ORA-00904: "MR"."MIGRATION_SERVER": invalid identifier\
also from other harmless queries like
apiMig.statusMigration(migration_rqst_id=1792544)
or e.g. via a simple curl GET
```
belforte@lxplus8s17/~> curl --cert $X509_USER_PROXY  --key $X509_USER_PROXY -H "Accept: application/json" https://cmsweb-testbed.cern.ch:8443/dbs/int/phys03/DBSMigrate/status
[{"error":{"reason":"DBSError Code:103 Description:DBS DB query error, e.g. mailformed SQL statement Function:dbs.executeAll Message: Error: ORA-00904: \"MR\".\"MIGRATION_SERVER\": invalid identifier\n","message":"","function":"dbs.migrate.StatusMigration","code":103},"http":{"method":"GET","code":400,"timestamp":"2022-07-23 12:40:38.534410811 +0000 UTC m=+23768.258016651","path":"/dbs/int/phys03/DBSMigrate/status","user_agent":"curl/7.59.0","x_forwarded_host":"cmsweb-testbed.cern.ch:8443","x_forwarded_for":"188.184.30.135","remote_addr":"10.100.59.128:32801"},"exception":400,"type":"HTTPError","message":"DBSError Code:103 Description:DBS DB query error, e.g. mailformed SQL statement Function:dbs.migrate.StatusMigration Message: Error: nested DBSError Code:103 Description:DBS DB query error, e.g. mailformed SQL statement Function:dbs.executeAll Message: Error: ORA-00904: \"MR\".\"MIGRATION_SERVER\": invalid identifier\n"}]belforte@lxplus8s17/~> 
```

hmm... let's have that fixed then I will try again to validate

**Comment by belforte** [comment]
I opened a JIRA ticket about the above error, since I suspect a config. problem  https://its.cern.ch/jira/browse/CMSKUBERNETES-165

Will resume testing once that is resolved

**Comment by vkuznet** [comment]
Ahh, it is DB issue, it looks like we did not updated database phys03 on testbed, I'll check on Monday.

**Comment by vkuznet** [comment]
Stefano, sorry for mess up. Turns out that we adjusted all DB schemas for production and testbed VMs, but we forgot that on k8s we used different DB account. Finally, the DB schema is adjusted on testbed k8s database and the issue you reported is not longer valid. Please proceed.

**Comment by belforte** [comment]
In other words, I get the error which I had reported at the start of https://github.com/dmwm/dbs2go/issues/63
where IIUC you say that the message simply indicates that a migration already exists for this block, but
1.  I do not find it when looking by block name and indeed block is not migrated
2. I thought that you had changed server to avoid reporting error in this case, but report the id of the ongoing migration or 0 as Id and state=4 in case the block is already at destination. But in this case I checked that block is not at destination.

So I do not know what to expect as resolution of #63, and I do not know what to do to get this block migrated.

**Comment by vkuznet** [comment]
Stefano, thanks for new example. I can confirm that I can duplicate it now. I  will report once it is fixed. It appears due to having single parent within parentage chain of blocks (sort of diamond diagram when initial block has two parents and each of them has the same another parent).

**Comment by belforte** [comment]
gosh... tricky situations, I fear we need to be prepared for everything in that area. Do not know if to be happy or sad that I hit this on my 3rd or 4th dataset try. Anyhow I will setup parallel publication in both production and int so we can test full chain
and hopefully get to the end of this.

**Comment by vkuznet** [comment]
Stefano, I addressed the issue and deployed new version. With this version I was able to migrate this block in my dev (`/dbs2go-migate` end-point) instance. I would appreciate if you'll try to resubmit this block again to see how it will go with testbed.

Said that, I understand that we should comprehensively test migration as it is very complex process, and the best way is to setup parallel replication as you did. I do perform tests but as we uncover new use-case I can't foresee each use-case and  test it accordingly until I get specific dataset/block for it which I do not know a-priory.

**Comment by belforte** [comment]
thanks Valentin. Submission worked now. Created 56 block migrations and the requested block is now pending (state 0). All looks good. [1]
I am going to setup parallel publication, which will trigger even more migrations since little of prod/global is in int/phys03 now. Let's see how it goes.
I suggest to close currently opened issues.

[1]
[{'create_by': '/DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica '
               'Nucleare/CN=Stefano Belforte belforte@infn.it',
  'creation_date': 1658779315,
  'last_modification_date': 1658779315,
  'last_modified_by': '/DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di '
                      'Fisica Nucleare/CN=Stefano Belforte belforte@infn.it',
  'migration_input': '/SingleMuon/Run2017E-UL2017_MiniAODv2-v1/MINIAOD#1d522d75-7490-4fff-9a21-198abe0b2bb9',
  'migration_request_id': 1821307,
  'migration_server': None,
  'migration_status': 0,
  'migration_url': 'https://cmsweb.cern.ch/dbs/prod/global/DBSReader',
  'retry_count': 0}]

**Comment by belforte** [comment]
hmm... migrations appear stuck.
56 were created, checking status for all I get a stable picture of 6 done (status=2), 50 pending (status=0) none in progress (status=1).
Is this a bad sign ?

**Comment by belforte** [comment]
I stand corrected, things started to move:
done/pend/inproc/fail = 8/47/1/0
need patience, I guess.

**Comment by belforte** [comment]
all done. !

**Comment by vkuznet** [comment]
ok, I'm glad things going forward. Please note, similar to Python server the Go server use a polling cycle, and it takes one migration at a time and proceed with that. Said that, I did not turn parallelization as I want first to ensure that sequential processing works normally. Once we'll confirm that, I'll enable more instances to test parallel execution. Feel free to send more migration requests to see if we will discover any other use-cases.

**Comment by vkuznet** [comment]
Stefano, I want to check with you if you have more good news on this ticket. Do you run more migration requests and/or do you running in parallel migration requests? Please share your results as I need to know how stable the code and if we need to fix anything else in order to understand how to move forward with this.

**Comment by belforte** [comment]
A ran a few more migrations by hand, all OK. But am late in a new publication script which makes correct calls to new server, to be run in parallel. Sorry, too many things.

**Comment by belforte** [comment]
the problem reported here was solved.
